# Generated by Django 4.0.3 on 2022-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ourteam_description_en_ourteam_description_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
